version: "3.9"
services:

  scrapper:
    restart: always
    env_file:
      - .env
    container_name: scrapper
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
